# Shared Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Shared Minecraft/Fabric - matches Create Fly's _unobfuscated setup
minecraft_version = 1.21.11
yarn_mappings = 1.21.11+build.5
loader_version = 0.19.2
fabric_version = 0.141.3+1.21.11
loom_version = 1.14-SNAPSHOT
maven_group = com.deeean
create_version = 6.0.8

# Ultimate Factory
uf_mod_version = 1.0.0
uf_archives_base_name = create-fly-ultimate-factory

# Create Fly Essential
ce_mod_version = 1.0.0
ce_archives_base_name = create-fly-essential
